BEGIN;
GRANT USAGE ON SCHEMA public TO bio_reagent_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO bio_reagent_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO bio_reagent_app;
ALTER DEFAULT PRIVILEGES FOR ROLE bio_reagent_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO bio_reagent_app;
ALTER DEFAULT PRIVILEGES FOR ROLE bio_reagent_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO bio_reagent_app;
COMMIT;
