BEGIN;
GRANT USAGE ON SCHEMA public TO bio_reagent_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO bio_reagent_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO bio_reagent_app;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bio_reagent_migrator') THEN
    EXECUTE 'ALTER DEFAULT PRIVILEGES FOR ROLE bio_reagent_migrator IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO bio_reagent_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES FOR ROLE bio_reagent_migrator IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO bio_reagent_app';
  END IF;
END
$$;
COMMIT;
